pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
      }
    }
    
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
    stage('package') {
      steps {
        sh 'npm run build'
      }
    }
  
    stage('version') {
      steps {
        sh 'node --version'
      }
    }
  }
}
